export const metadata = {
  title: "App Starter Onboarding",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <div className="container flex flex-col items-center justify-center   h-16">
          <h2 className="text-xl font-semibold ">App Starter</h2>
        </div>

        <div>{children}</div>
      </body>
    </html>
  );
}
