import MainNav from "@/components/main-nav";
import { Search } from "@/components/search";
import { UserNav } from "@/components/user-nav";

export const metadata = {
  title: "App Starter Dasboard",
  description: "Generated by create next app",
};

export default function DasboardLayout({ children }) {
  return (
    <html>
      <body>
        <div className="hidden flex-col md:flex">
          <div className="border-b">
            <div className="flex h-16 items-center px-4">
              <h2 className="text-2xl font-semibold px-4">App Starter</h2>

              <MainNav className="mx-6" />
              <div className="ml-auto flex items-center space-x-4">
                <Search />
                <UserNav />
              </div>
            </div>
          </div>
        </div>

        <div className="mx-10 my-5 border-1  ">{children}</div>
      </body>
    </html>
  );
}
